<?php
/**
 * Auto-generated by wp-scripts in a normal build.
 * Manually maintained here since we ship without a build step.
 *
 * Add any new wp.* API namespaces used in index.js to the dependencies array.
 */
return [
    'dependencies' => [
        'wp-blocks',
        'wp-block-editor',
        'wp-components',
        'wp-element',
        'wp-i18n',
    ],
    'version' => '1.0.5',
];
